#!/bin/bash
#

echo -n "Sisesta enda vanus:"; read vanus

if test $vanus -gt 0 -a $vanus -lt 11
then
	echo "Sa oled laps!"
elif test $vanus -ge 11 -a $vanus -lt 18
then
	echo "Sa oled noor!"
elif test $vanus -ge 18 -a $vanus -lt 63
then
	echo "Sa oled täiskasvanu!"
elif test $vanus -ge 63
then
	echo "Sa oled vanur!"
else
	echo "Oled sisestanud mittesobiva väärtuse!"
fi
