#!/bin/bash
#

echo -e "Sisesta suvaline taisarv: \c"; read suvaline

if [ $suvaline -eq 0 -o $suvaline -eq 1 ]	# Kui sisestatud arv on 1 või 0 siis...
then
	echo "$suvaline - ei ole algarv..."
else	 # muul juhul sooritatakse tehe:
	jaga=2
	yle=$(( $suvaline % $jaga ))
while [ $yle -ne 0 ] 	# edasi testitakse tehte tulemusi ning positiivse tulemuse korral tehakse järgmine tehe:
do
	jaga=$(($jaga + 1))
	yle=$(( $suvaline % $jaga ))
done
if [ $suvaline -eq $jaga ]	# Testitakse tehet, positiivse tulemuse korral väljastatakse vastus.
then
	echo "$suvaline - on algarv..."
else
	echo "$suvaline - ei ole algarv..."
fi
fi
