#!/bin/bash
#
#
echo -n "Sisesta kolmnurga esimene külg: "; read a	# Küsib kasutajalt külgi
echo -n "Sisesta kolmnurga teine külg: "; read b
echo -n "Sisesta kolmnurga kolmas külg: "; read c
echo "Kolmnurga esimene külg - $a, teine külg - $b, kolmas külg - $c..." 	# Väljastab eelnevalt sisestatud küljed
xx=$((( a + b + c )/2))
x1=$(( $xx - $a ))		# Kirjutasin niimoodi eraldi välja kuna viskas erroreid
x2=$(( $xx - $b ))
x3=$(( $xx - $c ))
x=$(echo "scale=2; sqrt($xx*$x1*$x2*$x3)" | bc -l)
echo "Teie kolmnurga pindala on $x"	# Väljastatakse lõppvastus


#
#  Skripti lõpp!!
#
