#!/bin/bash
#
#
echo -n "Sisesta ridade arv: "; read rida # Küsib väärtused
echo -n "Sisesta tarnide arv reas: "; read tarn # Nüüd on kasutaja enda teha mitu rida mitu sümbolit reas


i=x
for (( $i = 1; $i <= $rida; $i++ ))
do
	for (( j = 1; j <= $tarn; j++ ))
	do
		echo -n "$i "
	done
echo ""
done
