#!/bin/bash
#
#
echo -n "Sisesta ridade arv: "; read rida
echo -n "Sisesta tarnide arv reas: "; read tarn


i=x
for (( $i = 1; $i <= $rida; $i++ ))
do
	for (( j = 1; j <= $tarn; j++ ))
	do
		echo -n "$i "
	done
echo ""
done
