#!/bin/bash
#
#
echo -n "Sisesta ridade arv: "; read rida
echo -n "Sisesta tarnide arv reas: "; read tarn

hmm=$(( $rida - 1))
i=x
j=x
for i in {1..$rida.. $hmm}
do
	for (( j = 1; j <= $tarn; j++ ))
	do
		echo -n "* "
	done
echo $rida
done
