#!/bin/bash
#
#
echo -n "Sisesta ridade arv: "; read rida
echo -n "Sisesta tarnide arv reas: "; read tarn

for (( i = 1; i <= $rida; i++ ))
do

	for (( j = 1; j <= $tarn; j++ ))
	do
		if (($i == 1 || $i == $rida))
		then
			echo -n "X "
		elif (($j == 1 || $j == $tarn))
		then
			echo -n "X "
		else
			echo -n "  "
		fi
	done
echo ""
done
