#!/bin/bash
#
#
echo -n "Sisesta ridade arv: "; read rida
echo -n "Sisesta tarnide arv reas: "; read tarn

for (( i = 1; i <= $rida; i++ ))
do

	for (( j = 1; j <= $tarn; j++ ))
	do
		if (($i == 1 || $i == $rida)) # Kui on esimene ja viimane rida siis...
		then
			echo -n "X " # lisab ta kõik sübolid 
		elif (($j == 1 || $j == $tarn)) # Kui on vahepealne rida siis...
		then
			echo -n "X " # Lisab ta sübolid algusesse ja lõppu
		else
			echo -n "  " # Tekitab tühikud kujundi keskele
		fi
	done
echo ""
done
#Nii tekibki kujund...
# * * * * *
# *	  *
# *	  *
# * * * * *
