#!/bin/bash
#
#
echo -n "Sisesta ridade arv: "; read rida
for (( i = 1; i <= $rida; i++ ))	# Sooritab tehte -- Kõigepaelt on defineeritud i=1, i'd on nii palju kui sisestatud ridu ja see siis liidetakse i"le
do
tarne=$(($rida + 1 - $i))	# Arvutatakse välja tärnid
	for ((j == 1; j <= $tarne; j++))  # Siin on defineeritud j e tärnide arv reas
	do
		echo -n "X "
	done
echo " "
done
### See script ei tööta päris nii nagu võiks
